name: Compile Python for All Platforms

on:
  workflow_dispatch:
    inputs:
      script_path:
        description: 'Path to the Python script'
        required: true
        default: 'delete-duplicates.py'

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Replace with your desired Python version

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Compile Python script
        run: pyinstaller --onefile ${{ github.event.inputs.script_path }}

      - name: Upload compiled binary
        uses: actions/upload-artifact@v3
        with:
          name: compiled-binary-windows
          path: dist/*-Windows.exe

  build_mac:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Compile Python script
        run: pyinstaller --onefile ${{ github.event.inputs.script_path }}

      - name: Upload compiled binary
        uses: actions/upload-artifact@v3
        with:
          name: compiled-binary-mac
          path: dist/*-MacOS 

  build_linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Compile Python script
        run: pyinstaller --onefile ${{ github.event.inputs.script_path }}

      - name: Upload compiled binary
        uses: actions/upload-artifact@v3
        with:
          name: compiled-binary-linux
          path: dist/*-Linux
